### ISSUE TITLE
[Bug] Selecting the direct link option in file previews takes you directly to the filename

### ISSUE THREAD

**Issue by thetrueyoshifan** [UiharuKazari2008/sequenzia#16]
When trying to link a file from an instance, the created URL is simply just the file name, rather than a path to access it.
![image](https://user-images.githubusercontent.com/42860543/214507602-be291dab-fe21-43f9-807d-9c4a55c9f838.png)
This appears to happen with any files bigger than the 7mb limit, and it is universal between prerelease and production.

**Comment by UiharuKazari2008** [comment]
Solved in some prerelease version, I forgot 😄
